### ISSUE TITLE
Setting a Complex default value for a Widget does not seem to work

### ISSUE THREAD

**Issue by Dr-Dray** [DMS-Aus/Roam#266]
Hi guys,

I'm having issues trying to get a Widget's default value config working using the complex manual method with [Type] = layer-value

Basically no bugs or errors are reported in either the Config Manager or Roam App but capturing a new feature does not action any of the default settings I have set, when I'm trying to set the default value based on a non-geometry based Control Reference layer (ie. Dbf flat file) called [LUTs.dbf] in this case acting as a large Lookup table for the Form and used successfully for Widget filters in the same form etc.

I have tested the actual expression successfully in QGIS's Attribute Table Expression builder for that particular layer which only returns a single record in this case as it should, even though according to the docs, the first record of a selected set will be used if multiple are returned.

So the problem could be that either my default Expression format is not quite right as shown below; 
````
expression: ' "FIELDNAME" = ''LINSP'' AND "IS_DEFAULT" = ''YES'' '
expression: '[% "FIELDNAME" = ''LINSP'' AND "IS_DEFAULT" = ''YES'' %]'
````
or that your app can only use Geometry based layers in this config that are showing on the map and/or in the Current Extent as per your example based on the [Admin-guide -projectformat.md](https://github.com/DMS-Aus/Roam-docs/blob/master/docs/admin-guide/projectformat.md)
or non-spatial layers should be enabled for selection in the project maybe?

I have also tried building a simple expression instead via the Config Manager to get this info and that too is a bit troublesome since I can't use multiple WHERE sub-clauses (like AND, OR) in the getFeature function to achieve my result, but I'm new to QGIS so maybe there is a way to do this if somebody knows:
````
default: '[% attribute( getFeature(''LUTs'', ''IS_DEFAULT'', ''YES''), ''LIST_VAL'') %]'
````
I have also tried to simplify the Widget by removing the Filter part of the List widget and also changing the Widget type to just a pure Text version, but nothing so far seems to work in setting this control property. So what to do??

**[form.config] part snapshot:**
````
- config:
    allownull: false
    layer:
      filter: '"FIELDNAME" = ''LINSP'''
      key: list_desc
      layer: LUTs
      value: list_val
    orderbyvalue: false
  default:
    type: layer-value
    layer: LUTs
    expression: ' "FIELDNAME" = ''LINSP'' AND "IS_DEFAULT" = ''YES'' '
    field: list_val
  field: linsp
  hidden: false
  name: Linsp
  read-only-rules:
  - never
  rememberlastvalue: false
  required: false
  widget: List
````
