### ISSUE TITLE
Any way to update the values of the capture layer?

### ISSUE THREAD

**Issue by karzak** [DMS-Aus/Roam#391]
Two layers have a 1-to-many relationship. Layer A (Callback, a point layer) is the parent, and layer B (PropertyVisit, a point layer) is the child. In the form for PropertyVisit I relate the two records using the 'Capture value from field'. The `form.config` for the PropertyVisit form looks like this.

```
- _id: a0af59eb-4fbe-4c08-ae54-02403d53db66
  config: {}
  default:
    expression: within($geometry, buffer($roamgeometry, 10))
    field: record_uid
    layer: Callback
    type: layer-value
  default_events:
  - capture
  field: fk_callback_record_uid
  hidden: true
  name: Callback Uid
  read-only-rules:
  - never
  rememberlastvalue: false
  required: true
  widget: Text
```

What I want to know is if I can use `form.py` and update values in the parent Callback record based on what is collected in the child PropertyVisit record. To make it concrete, if the 'status' field in PropertyVisit is 'Complete', I would like to update the 'current_status' field in the related Callback record to 'Complete'. What I'm not sure is if I have access to layers beyond PropertyVisit in the PropertyVisit form.py, and if I do, how I access the other layer's attributes.
