### ISSUE TITLE
Config Manager error on exiting with Capture value from field

### ISSUE THREAD

**Issue by TonyFMCMC** [DMS-Aus/Roam#410]
I am trying to set up a simple Capture value from field.  When I re-open config manager, the Capture layer has defaulted back to another table (when I saved it and closed, the Capture Layer was 'sites') see image below.  Saving and closing generated two identical errors in C:\IntraMaps Roam\Roam Config Manager.exe.log as follows:
`Traceback (most recent call last):
  File "configmanager\ui\layerwidgets.pyc", line 764, in _save_current_widget
  File "configmanager\ui\layerwidgets.pyc", line 771, in _save_widget
  File "configmanager\ui\layerwidgets.pyc", line 802, in _get_widget_config
  File "configmanager\ui\layerwidgets.pyc", line 783, in _get_default_config
AttributeError: 'NoneType' object has no attribute 'name'`
Although the sites table does have a field called 'name'.

![image](https://user-images.githubusercontent.com/36878758/38234909-a6b01e02-3762-11e8-9edc-420b1e4f696f.png)
![image](https://user-images.githubusercontent.com/36878758/38235045-218ac1b8-3763-11e8-97d9-6c94922b7743.png)

I think there are two separate problems here;  I think maybe the display of 'EREmployees' instead of 'sites' is just a display issue, and then there is that it is finding a NoneType object.

Although the EREmployees table is not a geographic table, just data.

Windows 8.1, QGIS 2.18, Roam2.6.  Data format is MSSQL.

**Comment by TonyFMCMC** [comment]
Despite this error in Config Manager, it seems that the value **is** being successfully captured in Roam.

**Comment by bzeeb** [comment]
Suspect it is some issue with direct MSSQL connections and versioning between QGIS 2.18 and 2.16 (loaded in Roam).

Will investigate, we haven't tested live database layers extensively.

**Comment by TonyFMCMC** [comment]
This does appear to be a problem in config manager, failing to populate the field dropdown from the value in the form.config file, which has the correct value (sites) under the default:layer entry.
```
- _id: c89ace67-f35e-48ba-befc-368435ad37a9
  config: {}
  default:
    expression: intersects($geometry, buffer($roamgeometry,5) )
    field: name
    layer: sites
    type: layer-value
  default_events:
  - capture
  - save
  field: site
  hidden: false
  name: Site
  read-only-rules:
  - editing
  rememberlastvalue: false
  required: false
  widget: Text
```
